### ISSUE TITLE
[v6]CoreUIv4 final CSS polish needed

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/theme-coreuiv4#12]
Reported by Pedro: Borders on links are huge in CoreUI v4. Some stuff is missing or not aligned

![](https://user-images.githubusercontent.com/7188159/246906800-222c6b7d-10e5-4f2a-b15e-9c704f9b2620.png)

**Comment by tabacitu** [comment]
In addition, I've made a video going through the CoreUIv4 theme and mentioning the things that bother me. Please make a list of the ones that you agree with, and let's start taking them down 💪

[![](https://cdn.loom.com/sessions/thumbnails/a23774c829f54d039afe5ac172dd7036-with-play.gif)](https://www.loom.com/share/a23774c829f54d039afe5ac172dd7036)

https://www.loom.com/share/a23774c829f54d039afe5ac172dd7036?sid=2e8e1947-dc03-488d-ab50-5cb8234cbdea

**Comment by phpfour** [comment]
Hey @tabacitu, none of the issues highlighted in this task (including the ones in your video) exist anymore – my best guess would be when @karandatwani92 replaced the old demo CSS references with the updated CSS reference from CoreUI's CDN, we received the goodies. 

Examples:

![CleanShot 2023-07-10-06 18 44](https://github.com/Laravel-Backpack/theme-coreuiv4/assets/171715/6807060a-4a22-435a-af22-12577cfbc894)

![CleanShot 2023-07-10-06 19 15](https://github.com/Laravel-Backpack/theme-coreuiv4/assets/171715/20997331-5ce0-4951-b65b-76d7e70b712a)

This issue can be closed IMHO.

**Comment by tabacitu** [comment]
Hey @phpfour ,

I was talking about CoreUIv4 not CoreUIv2 😀

I think Karan's back and can take this over though. Right @karandatwani92 ?

**Comment by tabacitu** [comment]
Note: this is overdue. It was supposed to be done this week.
