### ISSUE TITLE
[v6][Bug] CoreUI v4 login page looks unfinished

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/theme-coreuiv4#14]
Pedro reported that, with this image:

![](https://user-images.githubusercontent.com/7188159/247069564-6b850962-42d1-475a-8e07-d2aa4f9752d5.png)

I also think that looks weird. Why is it missing the top margin? Why is the footer not fixed to the bottom of the page?

**Comment by karandatwani92** [comment]
Hey @tabacitu 
It's fine, no fix is required.
Tested on macOS, windows
Chrome, Safari

Please check on your side too and let's close it.

![image](https://github.com/Laravel-Backpack/theme-coreuiv4/assets/8214221/c0d76a6a-c611-4608-8622-a70e1f6ef4e5)

**Comment by pxpm** [comment]
Hey @karandatwani92 still experiencing the issue:
![image](https://github.com/Laravel-Backpack/theme-coreuiv4/assets/7188159/898a7bac-ee6c-4d8e-9ab2-b6a221d0f081)

**Comment by karandatwani92** [comment]
AAAAAAA!

OK! It worked for me on two different machines using two different screens on two different browsers.

Should we try republishing the assets on your local machine?

**Comment by pxpm** [comment]
@karandatwani92 backpack v6 don't have assets to publish. 

Maybe you are overwriting something in your app `resources/` ?

**Comment by karandatwani92** [comment]
Naa ~ I'm running a fresh install, with no overwriting.
