### ISSUE TITLE
Missing Attributes Log Errors

### ISSUE THREAD

**Issue by karandatwani92** [Laravel-Backpack/theme-coreuiv4#38]
##### theme-coreuiv4
https://github.com/Laravel-Backpack/theme-tabler/blob/main/config/theme-tabler.php

##### theme-coreuiv2(missing attributes)
https://github.com/Laravel-Backpack/theme-coreuiv2/blob/main/config/theme-coreuiv2.php

##### theme-coreuiv4(missing attributes)
https://github.com/Laravel-Backpack/theme-coreuiv4/blob/main/config/theme-coreuiv4.php

#### Error type(this could be any missing key)
![Screenshot 2023-07-12 at 7 18 02 PM](https://github.com/Laravel-Backpack/theme-coreuiv4/assets/8214221/234ebce8-a1b4-47a2-a905-ea095b2daf3e)

**Comment by tabacitu** [comment]
It's been fixed on all themes, on `main` - just hadn't been tagged yet. If I remember correctly it was @pxpm who implemented the fix. 

I've just tagged new versions of CRUD and all 3 themes. A `composer update` should pull the new ones and fix this problem. Please let me know if it doesn't and we'll reopen.

Cheers!

**Comment by karandatwani92** [comment]
Hey @tabacitu, It's not fixed.
And, I'm using the updated version.

**Comment by tabacitu** [comment]
I have no idea, to be honest. If you install v6 and all themes in a new project, do you still get the problem? Or is it isolated to this one project you have?

**Comment by karandatwani92** [comment]
> I have no idea, to be honest. If you install v6 and all themes in a new project, do you still get the problem? Or is it isolated to this one project you have?

@tabacitu I created a new project, a fresh installation and the **bug exists.**

**Comment by tabacitu** [comment]
We discussed in today's team meeting. A good fix is probably to add the missing config to Backpack's `config/ui.php`. If it's used in DataTables / ListOperation, then it's a config all themes should have, not just one. And `ui.php` is exactly that - the fallback config for all themes.

**Comment by karandatwani92** [comment]
Solved https://github.com/Laravel-Backpack/CRUD/pull/5230
