### ISSUE TITLE
[Bug] Design seems to be broken on the new version 

### ISSUE THREAD

**Issue by Astriel** [Laravel-Backpack/theme-coreuiv4#50]
# Bug report

### What I did

I've integrated the V6 of Backpack with the V4 of the UI. Everything went well. I've switched to another branch, then came back on the one which includes Backpack, I've made a composer update, but now the whole UI is broken. Sounds like it's something maybe linked to basset. Someone else of the community is facing the same problem.

![image](https://github.com/Laravel-Backpack/theme-coreuiv4/assets/4165153/777a15de-bc91-4c71-9731-f25dbb96f720)

Related issues : 

- https://github.com/Laravel-Backpack/basset/issues/95
- https://github.com/Laravel-Backpack/basset/issues/88

### What I've already tried to fix it

- Install the project again and the components
- Compiling basset
- Changing to UI V2 which is working

### Context to replicate the bug - Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

```
### PHP VERSION:
PHP 8.1.2 (cli) (built: Jan 19 2022 10:18:23) (ZTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.1.2, Copyright (c) Zend Technologies

### LARAVEL VERSION:
10.21.1.0

### BACKPACK PACKAGE VERSIONS:
backpack/basset: 1.2.0
backpack/crud: 6.2.0
backpack/devtools: 2.0.3
backpack/generators: v4.0.2
backpack/permissionmanager: 7.0.1
backpack/pro: 2.0.11
backpack/theme-coreuiv4: 1.1.0
```

**Comment by promatik** [comment]
Hi again @Astriel, I'll close this one because I'm sure it's related with https://github.com/Laravel-Backpack/basset/issues/95 👌

**Comment by Astriel** [comment]
Hello @promatik I've update Backpack and basset ... But the problem is still here. Basset is working fine now, I've got no error, but the whole UI is still broken.
