### ISSUE TITLE
[Bug] Topbar left - not rendered as it should

### ISSUE THREAD

**Issue by GregaUNK** [Laravel-Backpack/theme-coreuiv4#56]
# Bug report

### What I did

I copied  topbar_left_content.blade.php and uncommented li elements.

### What I expected to happen

I expect it to be rendered as on basic demo coreui4 template. But its not.
![Screenshot 2024-08-24 at 11 09 13](https://github.com/user-attachments/assets/c4255b58-c7e8-44e7-92bc-7e75027c34f9)

### What happened

![Screenshot 2024-08-24 at 11 07 27](https://github.com/user-attachments/assets/20e76e73-4135-4b67-84c9-72891e55521a)

### What I've already tried to fix it

I disabled all of my custom CSS/JS assets. I have not changed/override any default theme structure.

### Is it a bug in the latest version of Backpack?

Yes.

### PHP VERSION:
8.3.7

### PHP EXTENSIONS:
Core, date, libxml, openssl, pcre, sqlite3, zlib, bcmath, bz2, calendar, ctype, curl, dba, dom, hash, FFI, fileinfo, filter, ftp, gd, gettext, gmp, json, iconv, intl, SPL, ldap, mbstring, session, standard, odbc, pcntl, exif, mysqlnd, PDO, pdo_dblib, pdo_mysql, PDO_ODBC, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, pspell, random, readline, Reflection, mysqli, shmop, SimpleXML, soap, sockets, sodium, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xml, xmlreader, xmlwriter, xsl, zip, Zend OPcache

### LARAVEL VERSION:
10.48.20.0

### BACKPACK PACKAGE VERSIONS:
backpack/basset: 1.3.5
backpack/crud: 6.7.30
backpack/generators: v4.0.5
backpack/logmanager: v5.0.2
backpack/permissionmanager: 7.2.1
backpack/pro: 2.1.7
backpack/revise-operation: 2.0.0
backpack/theme-coreuiv2: 1.2.5
backpack/theme-coreuiv4: 1.1.2
backpack/theme-tabler: 1.2.11

**Comment by karandatwani92** [comment]
Hey @GregaUNK 

I've escalated the issue to my colleague for the Fix. Thanks for reporting the issue.

**Comment by ahmadmobaraki** [comment]
Hey @GregaUNK , did you fix the issue? any workaround?

**Comment by GregaUNK** [comment]
Hi @ahmadmobaraki ,

no, Iam @pxpm to fix that. In the meantime, I’m using the standard sidebar.
